### ISSUE TITLE
DOCUMENTATION UPDATE - Update README to Reflect Source Requirements

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_facebook_ads#12]
**Are you a Fivetran customer?** 

Fivetran created request

**Is your feature request related to a problem? Please describe.**
 
This repo does not contain the required reports needed to run the final models. We should update the repo to include these requirements.

**Describe alternatives you've considered**
 
Point users to the source package. This is not ideal and should all be included in this repo as well to allow users to look in just one location.

**Additional context**

The similar update we made to the dbt_google_ads repo has proven helpful. The same can be helpful here.

**Comment by pawelngei** [comment]
Done in https://github.com/fivetran/dbt_facebook_ads/pull/13
