### ISSUE TITLE
FEATURE - orders and revenue added to tables

### ISSUE THREAD

**Issue by cbeem1** [fivetran/dbt_facebook_ads#8]
**Are you a Fivetran customer?** 
Connor Beem, Sr. Growth Data Analyst, Cameo

**Is your feature request related to a problem? Please describe.**
No problem, just would like orders and revenue in these tables as well! 

**Describe the solution you'd like**
adding in orders and revenue from facebook `basic_ad_actions`
 
**Describe alternatives you've considered**
adding these in manually from this table 

**Additional context**

**Please indicate the level of urgency and business impact of this request** 
definitely needed for reporting! 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ /] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @cbeem1 👋 

Thanks for opening this issue! It looks like to integrate the orders and revenue from `basic_ad_actions` would require bringing in the table at the [source package](https://github.com/fivetran/dbt_facebook_ads_source) and scoping out how to include these fields into our final models. I can add this Feature Request to our next sprint to be scoped out and assigned accordingly. I will be sure to have a member of our team respond back here once it has been assigned to continue communication.

It would be extremely helpful if you by chance have already included these metrics to the final models manually. If you have, would you be able to share the query here as it will help us in updating the package.

Thanks again! 🎉

**Comment by fivetran-joemarkiewicz** [comment]
@cbeem1 is this still a request you would like to have added to the facebook package?

**Comment by fivetran-joemarkiewicz** [comment]
After chatting with @cbeem1 this request is no longer needed. Closing the ticket, but open to readdressing if other customers have this request in the future.
